name: Build and push Docker-Images
run-name: Build and Push Docker-Images

on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
      docker_build_path:
        required: false
        default: .
        type: string
      service:
        required: true
        type: string
    secrets:
      GC_SERVICE_ACCOUNT:
        required: true
      GC_SERVICE_ACCOUNT_SECRET:
        required: true
      GC_PROJECT_ID:
        required: true
      REACT_JS_ENV:
        required: false

env:
  DOCKER_IMG_PATH: europe-west1-docker.pkg.dev/${{ secrets.GC_PROJECT_ID  }}/docker-repo/${{ inputs.service }}
  GOOGLE_APPLICATION_CREDENTIALS:  ${{ github.workspace }}/${{ secrets.GC_SERVICE_ACCOUNT }}.json
  SERVICE_ACCOUNT_EMAIL: ${{ secrets.GC_SERVICE_ACCOUNT }}@${{ secrets.GC_PROJECT_ID }}.iam.gserviceaccount.com

jobs:

  set-new-version:
    uses: msi-cad-vw/workflows/.github/workflows/docker-set-version.yml@main
    with:
      service: ${{ inputs.service }}

    secrets:
      GC_SERVICE_ACCOUNT: ${{ secrets.GC_SERVICE_ACCOUNT }}
      GC_SERVICE_ACCOUNT_SECRET: ${{ secrets.GC_SERVICE_ACCOUNT_SECRET }}
      GC_PROJECT_ID: ${{ secrets.GC_PROJECT_ID }}

  build:
    needs: [set-new-version]
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate to Google Cloud
        run: |
          echo "${{ secrets.GC_SERVICE_ACCOUNT_SECRET }}" | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS
          gcloud auth activate-service-account \
            "${{ secrets.GC_SERVICE_ACCOUNT_EMAIL }}" --key-file=$GOOGLE_APPLICATION_CREDENTIALS
          gcloud config set project ${{ secrets.GC_PROJECT_ID }}
      
      - name: Docker auth
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet
      
      - uses: actions/checkout@v4

      - name: Create frontend env
        if: ${{ inputs.service == 'frontend' }}
        run: |
          cd app
          echo "${{ secrets.REACT_JS_ENV }}" > .env
          cat .env
          ls -la

          while IFS='=' read -r name value; do
            export "$name=$value"
          done < .env

          npm install
          npm run build
      
      - name: Build Docker Image
        run: docker build --tag ${{ inputs.service }}:${{ needs.set-new-version.outputs.version }} --file ${{ inputs.dockerfile }} ${{ inputs.docker_build_path }}

      - name: Tag Docker image
        run: docker tag ${{ inputs.service }}:${{ needs.set-new-version.outputs.version }} ${{ env.DOCKER_IMG_PATH }}:${{ needs.set-new-version.outputs.version }}

      - name: Push Docker Image
        run: docker push ${{ env.DOCKER_IMG_PATH }}:${{ needs.set-new-version.outputs.version }}
