name: Test dotnet application

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      name: # e.g. Msi.Cad.FacilityManagement
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      # You can test your matrix by printing the current dotnet version
      - name: Display dotnet version
        run: dotnet --version

      - name: Install dependencies
        run: dotnet restore "${{ inputs.name }}/${{ inputs.name }}.Presentation/${{ inputs.name }}.Presentation.csproj"

      # - name: Test with dotnet
      #   run: dotnet test "${{ inputs.name }}.dll" --logger trx
