name: Upgrade Helm Services

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      cluster: 
        required: false
        type: string
        default: msi-cad-vw-cluster
      database:
        required: false
        type: string
        default: msi-cad-vw-database
      bucket:
        required: false
        type: string
        default: msi-cad-vw-bucket

    secrets:
      GC_SERVICE_ACCOUNT:
        required: true
      GC_SERVICE_ACCOUNT_SECRET:
        required: true
      GC_PROJECT_ID:
        required: true
      GC_BACKEND_BUCKET:
        required: true

env:
  HELM_CHART_PATH: oci://europe-west1-docker.pkg.dev/${{ secrets.GC_PROJECT_ID  }}/helm-repo
  GOOGLE_APPLICATION_CREDENTIALS:  ${{ github.workspace }}/${{ secrets.GC_SERVICE_ACCOUNT }}.json
  SERVICE_ACCOUNT_EMAIL: ${{ secrets.GC_SERVICE_ACCOUNT }}@${{ secrets.GC_PROJECT_ID }}.iam.gserviceaccount.com
  REGION: europe-west1-c 

jobs:
  check-kubernetes:
    name: 'Check Kubernetes'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      run: |
        echo "${{ secrets.GC_SERVICE_ACCOUNT_SECRET }}" | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS
        echo $SERVICE_ACCOUNT_EMAIL
        gcloud auth activate-service-account $SERVICE_ACCOUNT_EMAIL --key-file=$GOOGLE_APPLICATION_CREDENTIALS
        gcloud config set project ${{ secrets.GC_PROJECT_ID }}

    # Get the GKE credentials so we can deploy to the cluster
    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
      with:
        cluster_name: ${{ inputs.cluster }}
        location: ${{ env.REGION }}
        project_id: ${{ secrets.GC_PROJECT_ID }}

  upgrade-kubernetes:
    name: 'Upgrade Kubernetes'
    runs-on: ubuntu-latest
    needs: [
        check-kubernetes
    ]
    if: ${{ always() && !cancelled() && needs.check-kubernetes.result == 'success' }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      run: |
        echo "${{ secrets.GC_SERVICE_ACCOUNT_SECRET }}" | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS
        echo $SERVICE_ACCOUNT_EMAIL
        gcloud auth activate-service-account $SERVICE_ACCOUNT_EMAIL --key-file=$GOOGLE_APPLICATION_CREDENTIALS
        gcloud config set project ${{ secrets.GC_PROJECT_ID }}

    # Get the GKE credentials so we can deploy to the cluster
    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
      with:
        cluster_name: ${{ inputs.cluster }}
        location: ${{ env.REGION }}
        project_id: ${{ secrets.GC_PROJECT_ID }}

    - name: Docker auth
      run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet
  
    - name: Download Tenants.json from Bucket and print tenants
      run: |
        gcloud storage cp gs://${{ secrets.GC_BACKEND_BUCKET }}/tenants.json tenants.json
        tenants=$(jq -r '.[].name' tenants.json)
        for tenant in $tenants; do
          echo $tenant
        done
    
    - name: Upgrade services with helm - Frontend and Gateway
      run: |
        helm upgrade gateway ${{ env.HELM_CHART_PATH }}/infrastructure/helm
        helm upgrade frontend ${{ env.HELM_CHART_PATH }}/frontend/helm
        
    - name: Upgrade Authentication
      run: |
        helm upgrade authentication ${{ env.HELM_CHART_PATH }}/authentication/helm --set resources.database=${{inputs.database}} --set resources.bucket=${{ inputs.bucket }}

    - name: Start backend for each tenant with helm
      run: |
        tenants=$(jq -r '.[].name' tenants.json)
        for tenant in $tenants; do
          helm upgrade parkspace-$tenant ${{ env.HELM_CHART_PATH }}/backend/helm --set namespace=$tenant --set resources.database=${{inputs.database}} --set resources.bucket=${{ inputs.bucket }}
        done

    - name: On failure
      if: failure()
      run: |
        echo "Services not running"
