name: Upgrade Helm Services

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
    secrets:
      GC_SERVICE_ACCOUNT:
        required: true
      GC_SERVICE_ACCOUNT_SECRET:
        required: true
      GC_PROJECT_ID:
        required: true

env:
  GOOGLE_APPLICATION_CREDENTIALS:  ${{ github.workspace }}/${{ secrets.GC_SERVICE_ACCOUNT }}.json
  SERVICE_ACCOUNT_EMAIL: ${{ secrets.GC_SERVICE_ACCOUNT }}@${{ secrets.GC_PROJECT_ID }}.iam.gserviceaccount.com
  CLUSTER: msi-cad-vw-cluster
  REGION: europe-west1-c 

jobs:
  check-kubernetes:
    name: 'Check Kubernetes'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./helm

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      run: |
        echo "${{ secrets.GC_SERVICE_ACCOUNT_SECRET }}" | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS
        echo $SERVICE_ACCOUNT_EMAIL
        gcloud auth activate-service-account $SERVICE_ACCOUNT_EMAIL --key-file=$GOOGLE_APPLICATION_CREDENTIALS
        gcloud config set project ${{ secrets.GC_PROJECT_ID }}

    # Get the GKE credentials so we can deploy to the cluster
    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
      with:
        cluster_name: ${{ env.CLUSTER }}
        location: ${{ env.REGION }}
        project_id: ${{ secrets.GC_PROJECT_ID }}

  upgrade-kubernetes:
    name: 'Upgrade Kubernetes'
    runs-on: ubuntu-latest
    needs: [
        check-kubernetes
    ]
    if: ${{ always() && !cancelled() && needs.check-kubernetes.result == 'success' }}

    defaults:
      run:
        shell: bash
        working-directory: ./helm

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      run: |
        echo "${{ secrets.GC_SERVICE_ACCOUNT_SECRET }}" | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS
        echo $SERVICE_ACCOUNT_EMAIL
        gcloud auth activate-service-account $SERVICE_ACCOUNT_EMAIL --key-file=$GOOGLE_APPLICATION_CREDENTIALS
        gcloud config set project ${{ secrets.GC_PROJECT_ID }}

    # Get the GKE credentials so we can deploy to the cluster
    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
      with:
        cluster_name: ${{ env.CLUSTER }}
        location: ${{ env.REGION }}
        project_id: ${{ secrets.GC_PROJECT_ID }}

    - name: Download Tenants.json from Bucket and print tenants
      run: |
        gcloud storage cp gs://msi-cad-vw-terraform-backend/tenants.json tenants.json
        tenants=$(jq -r '.[].name' tenants.json)
        for tenant in $tenants; do
          echo $tenant
        done
    
    - name: Upgrade services with helm - Frontend and Gateway
      run: |
        helm upgrade gateway ./infrastructure/
        helm upgrade frontend ./frontend/  

    - name: Start backend for each tenant with helm
      run: |
        tenants=$(jq -r '.[].name' tenants.json)
        for tenant in $tenants; do
          helm upgrade parkspace-$tenant ./backend/ --set namespace=$tenant
        done

    - name: On failure
      if: failure()
      run: |
        echo "Kubernetes Cluster is not running"