name: Start Application and Cluster

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

env:
  GOOGLE_APPLICATION_CREDENTIALS:  ${{ github.workspace }}/${{ secrets.GC_SERVICE_ACCOUNT }}.json
  SERVICE_ACCOUNT_EMAIL: ${{ secrets.GC_SERVICE_ACCOUNT }}@${{ secrets.GC_PROJECT_ID }}.iam.gserviceaccount.com


jobs:
  set-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-output.outputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Read Version from File
        id: read-version
        run: echo "version=$(cat version.txt)" >> $GITHUB_ENV

      - name: Increment Version
        id: set-output
        run: |
          current_version=$(cat version.txt)
          new_version=$(echo $current_version | awk -F. '{print $1"."$2"."$3+1}')
          echo "New Version: $new_version"
          echo "$new_version" > version.txt
          echo "version=$new_version" >> $GITHUB_ENV
          echo "::set-output name=version::$new_version"

      - name: Commit Updated Version
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add version.txt
          git commit -m "Bump version to ${{ steps.set-output.outputs.version }}"
          git push origin ${{ inputs.branch }}